version: '3.3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./../site/:/var/www
    depends_on:
      - php
    ports:
      - 80:80

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./../site/:/var/www
    env_file:
      - .env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_CHARSET: ${MYSQL_CHARSET}
    ports:
      - 9010:9000

  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - 3309:3306

  adminer:
    build:
      context: .
      dockerfile: Dockerfile-adminer
    ports:
      - 9000:8080